const laosData = {
    //   "Attapeu": {
    //     "Samakkixay": {
    //       en: ["Ban Xaysettha", "Ban Somsanouk", "Ban Donsavanh"],
    //       la: ["ບ້ານໄຊເສດທາ", "ບ້ານສົມສານຸກ", "ບ້ານດອນສະຫວັນ"]
    //     },
    //     "Sanamxay": {
    //       en: ["Ban Phouampha", "Ban Vangphai"],
    //       la: ["ບ້ານພູອຳພາ", "ບ້ານວັງໄພ"]
    //     },
    //     "Sanxay": {
    //       en: ["Ban Nonghin", "Ban Phouhouay"],
    //       la: ["ບ້ານໜອງຫິນ", "ບ້ານພູຫ່ວາຍ"]
    //     }
    //   },
    //   "Bokeo": {
    //     "Houayxay": { en: ["Ban Meungneua", "Ban Done"], la: ["ບ້ານເມືອງເໜືອ", "ບ້ານດອນ"] },
    //     "Meung": { en: ["Ban Meung", "Ban Sopmeung"], la: ["ບ້ານເມືອງ", "ບ້ານຊອບເມືອງ"] },
    //     "Paktha": { en: ["Ban Paknga", "Ban Namkeung"], la: ["ບ້ານປາກທາ", "ບ້ານນ້ຳແກງ"] }
    //   },
    //   "Bolikhamxay": {
    //     "Paksan": { en: ["Ban Keun", "Ban Namsanam"], la: ["ບ້ານເກືອນ", "ບ້ານນ້ຳສະນະນາມ"] },
    //     "Borikhane": { en: ["Ban Nakhang", "Ban Phon"], la: ["ບ້ານນາຄັງ", "ບ້ານພອນ"] },
    //     "Khamkeut": { en: ["Ban Lak Sao", "Ban Viengthong"], la: ["ບ້ານລັກເຊາ", "ບ້ານວຽງທອງ"] }
    //   },
    //   "Champasak": {
    //     "Pakse": { en: ["Ban Lak 20", "Ban Thongphong"], la: ["ບ້ານລັກ 20", "ບ້ານທ້ອງພອງ"] },
    //     "Pathoumphone": { en: ["Ban Nongphaya", "Ban Na"], la: ["ບ້ານໜອງພະຍາ", "ບ້ານນາ"] },
    //     "Khong": { en: ["Ban Don Det", "Ban Don Khon"], la: ["ບ້ານດອນເດັດ", "ບ້ານດອນຄອນ"] }
    //   },

    "Vientiane Prefecture": {

        "Chanthabuly": [
            { la: "ບ້ານໜອງປີງ", en: "Nong Ping Village" },
            { la: "ບ້ານບໍ່ນາງົວ", en: "Bo Nangvua Village" },
            { la: "ບ້ານຫ້ວຍຫົງ", en: "Huay Hong Village" },
            { la: "ບ້ານໂພນສະຫວ່າງ", en: "Phon Savang Village" },
            { la: "ບ້ານໜອງທາເໜືອ", en: "Nong Tha North Village" },
            { la: "ບ້ານໜອງທາໃຕ້", en: "Nong Tha South Village" },
            { la: "ບ້ານດອນແດງ", en: "Don Daeng Village" },
            { la: "ບ້ານໂພນຕ້ອງສະຫວາດ", en: "Phon Tong Savat Village" },
            { la: "ບ້ານດົງປາແຫຼບ", en: "Dong Pa Laep Village" },
            { la: "ບ້ານໂພນຕ້ອງຈອມມະນີ", en: "Phon Tong Chommani Village" },
            { la: "ບ້ານຮ່ອງແຊງ", en: "Hong Saeng Village" },
            { la: "ບ້ານຮ່ອງໄກ່ແກ້ວ", en: "Hong Kai Kaew Village" },
            { la: "ບ້ານທົ່ງສາງນາງ", en: "Thung Sang Nang Village" },
            { la: "ບ້ານສະຫວ່າງ", en: "Sawang Village" },
            { la: "ບ້ານຮ່ອງຄ້າ", en: "Hong Kha Village" },
            { la: "ບ້ານທົ່ງຕູມ", en: "Thung Tumm Village" },
            { la: "ບ້ານດົງໝ້ຽງ", en: "Dong Mieng Village" },
            { la: "ບ້ານສີດຳດວນ", en: "Si Dam Duan Village" },
            { la: "ບ້ານສີບຸນເຮືອງ", en: "Si Bun Heuang Village" },
            { la: "ບ້ານຂົວຫຼວງ", en: "Khoua Luang Village" },
            { la: "ບ້ານສີສະຫວາດ", en: "Si Savat Village" },
            { la: "ບ້ານທົ່ງຂັນຄຳ", en: "Thung Khan Kham Village" },
            { la: "ບ້ານສີຫອມ", en: "Si Hom Village" },
            { la: "ບ້ານອານຸ", en: "Anu Village" },
            { la: "ບ້ານສາຍລົມ", en: "Sai Lom Village" },
            { la: "ບ້ານຫັດສະດີ", en: "Hatsadi Village" },
            { la: "ບ້ານຫາຍໂສກ", en: "Hai Sok Village" },
            { la: "ບ້ານວັດຈັນ", en: "Wat Chan Village" },
            { la: "ບ້ານມີໄຊ", en: "Mee Sai Village" },
            { la: "ບ້ານຊຽງຍືນ", en: "Xieng Yun Village" },
            { la: "ບ້ານສາຍນໍ້າເງິນ", en: "Sai Nam Ngeun Village" }
        ],

        "Xaysettha": [
            { la: "ບ້ານຈອມມະນີເໜືອ", en: "Chommani North Village" },
            { la: "ບ້ານຈອມມະນີກາງ", en: "Chommani Central Village" },
            { la: "ບ້ານຈອມມະນີໃຕ້", en: "Chommani South Village" },
            { la: "ບ້ານໂພນພະເນົາ", en: "Phon Phaneo Village" },
            { la: "ບ້ານໂພນເຄັງ", en: "Phon Kheng Village" },
            { la: "ບ້ານໜອງສ້າງທໍ່", en: "Nong Sang Tho Village" },
            { la: "ບ້ານໂພນສະອາດ", en: "Phon Sad Village" },
            { la: "ບ້ານທາດຫຼວງເໜືອ", en: "That Luang North Village" },
            { la: "ບ້ານໜອງບອນ", en: "Nong Bon Village" },
            { la: "ບ້ານໂພນໄຊ", en: "Phon Sai Village" },
            { la: "ບ້ານນາໄຊ", en: "Na Sai Village" },
            { la: "ບ້ານຝາຍ", en: "Phai Village" },
            { la: "ບ້ານວຽງຈະເລີນ", en: "Vieng Jaleun Village" },
            { la: "ບ້ານທາດຫຼວງກາງ", en: "That Luang Central Village" },
            { la: "ບ້ານທາດຫຼວງໃຕ້", en: "That Luang South Village" },
            { la: "ບ້ານຮ່ອງແກ", en: "Hong Kae Village" },
            { la: "ບ້ານສີສັງວອນ", en: "Si Sang Vorn Village" },
            { la: "ບ້ານສະພັງໝໍ້", en: "Saphang Moh Village" },
            { la: "ບ້ານໂພນທັນເໜືອ", en: "Phon Than North Village" },
            { la: "ບ້ານໂພນທັນໃຕ້", en: "Phon Than South Village" },
            { la: "ບ້ານຮ່ອງສຸພາບ", en: "Hong Suphap Village" },
            { la: "ບ້ານໂນນສະຫວັນ", en: "Non Savanh Village" },
            { la: "ບ້ານໜອງໜ່ຽງ", en: "Nong Nieng Village" },
            { la: "ບ້ານໂນນສະຫງ່າ", en: "Non Sanga Village" },
            { la: "ບ້ານອາມອນ", en: "Amon Village" },
            { la: "ບ້ານແສງສະຫວ່າງ", en: "Saeng Savang Village" },
            { la: "ບ້ານໂຊກຄຳ", en: "Sok Kham Village" },
            { la: "ບ້ານວັງຊາຍ", en: "Vang Say Village" },
            { la: "ບ້ານໂນນສະຫວ່າງ", en: "Non Savang Village" },
            { la: "ບ້ານຫົວຂົວ", en: "Hua Khuo Village" },
            { la: "ບ້ານໂນນຄໍ້ເໜືອ", en: "Non Kho North Village" },
            { la: "ບ້ານຄຳສະຫວາດ", en: "Kham Savat Village" },
            { la: "ບ້ານໂນນຫວາຍ", en: "Non Huay Village" },
            { la: "ບ້ານເມືອງນ້ອຍ", en: "Muang Noi Village" },
            { la: "ບ້ານຊຽງດາ", en: "Xieng Da Village" },
            { la: "ບ້ານຂາມງອຍ", en: "Kham Ngoy Village" },
            { la: "ບ້ານນາສ້າງໄພ", en: "Na Sang Phai Village" },
            { la: "ບ້ານສົມສະຫງ່າ", en: "Som Sanga Village" },
            { la: "ບ້ານໄຮຄຳ", en: "Hai Kham Village" },
            { la: "ບ້ານນາຄວາຍກາງ", en: "Na Khuay Central Village" },
            { la: "ບ້ານນາຄວາຍໃຕ້", en: "Na Khuay South Village" },
            { la: "ບ້ານໂຊກໃຫຍ່", en: "Sok Yai Village" },
            { la: "ບ້ານໂຊກນ້ອຍ", en: "Sok Noi Village" },
            { la: "ບ້ານຊຳເຄ້", en: "Cham Khe Village" },
            { la: "ບ້ານໂພນທອງ", en: "Phon Thong Village" },
            { la: "ບ້ານນາບຽນ", en: "Na Bien Village" },
            { la: "ບ້ານດຸ່ງໃຫຍ່", en: "Dung Yai Village" },
            { la: "ບ້ານດຸ່ງກາງ", en: "Dung Central Village" },
            { la: "ບ້ານນາໄຫ", en: "Na Hai Village" },
            { la: "ບ້ານນາໂນ", en: "Na No Village" },
            { la: "ບ້ານຈອມສີ", en: "Chom Si Village" },
            { la: "ບ້ານໂນນຄໍ້ໃຕ້", en: "Non Kho South Village" }
        ],

        "Sikhottabong": [
            { la: "ບ້ານນາຄຳ", en: "Na Kham Village" },
            { la: "ບ້ານອູບມຸງ", en: "Ub Mung Village" },
            { la: "ບ້ານໜອງປາໃນ", en: "Nong Pa Nai Village" },
            { la: "ບ້ານວັດໄຕນ້ອຍທ່າ", en: "Wat Tai Noi Tha Village" },
            { la: "ບ້ານວັດໄຕນ້ອຍທົ່ງ", en: "Wat Tai Noi Thong Village" },
            { la: "ບ້ານໜອງສະໂນຄຳ", en: "Nong Sanokham Village" },
            { la: "ບ້ານວັດໄຕໃຫຍ່ທ່າ", en: "Wat Tai Yai Tha Village" },
            { la: "ບ້ານອາກາດ", en: "A Kat Village" },
            { la: "ບ້ານເມືອງວາທົ່ງ", en: "Muang Vathong Village" },
            { la: "ບ້ານສີໄຄທ່າ", en: "Si Khai Tha Village" },
            { la: "ບ້ານສີໄຄທົ່ງໃຕ້", en: "Si Khai Thong Tai Village" },
            { la: "ບ້ານສີໄຄທົ່ງເໜືອ", en: "Si Khai Thong Nuea Village" },
            { la: "ບ້ານຍາພະ", en: "Ya Pha Village" },
            { la: "ບ້ານສີບຸນເຮືອງທ່າ", en: "Si Bun Hueng Tha Village" },
            { la: "ບ້ານສີບຸນເຮືອງທົ່ງ", en: "Si Bun Hueng Thong Village" },
            { la: "ບ້ານສີຊົມຊື່ນ", en: "Si Chom Suen Village" },
            { la: "ບ້ານໂນນສະຫວ່າງ", en: "Non Savan Village" },
            { la: "ບ້ານເກົ້າລ້ຽວ", en: "Kao Liao Village" },
            { la: "ບ້ານດ່ານຄຳ", en: "Dan Kham Village" },
            { la: "ບ້ານໂນນຂີ້ເຫຼັກ", en: "Non Khi Lek Village" },
            { la: "ບ້ານໂນນແກ້ວ", en: "Non Kaew Village" },
            { la: "ບ້ານໂພນສະຫວາດເໜືອ", en: "Phon Savad Nuea Village" },
            { la: "ບ້ານໂພນສົມບູນ", en: "Phon Sombun Village" },
            { la: "ບ້ານຕາດທອງ", en: "Tat Thong Village" },
            { la: "ບ້ານໜອງດາ", en: "Nong Da Village" },
            { la: "ບ້ານໃໝ່", en: "Mai Village" },
            { la: "ບ້ານຫ້ວຍຫ້ອມ", en: "Huay Hom Village" },
            { la: "ບ້ານອ່າງໃຫ່ຍ", en: "Ang Yai Village" },
            { la: "ບ້ານໂພສີ", en: "Pho Si Village" },
            { la: "ບ້ານນາແຮ່", en: "Na Hae Village" },
            { la: "ບ້ານວຽງສະຫັວນ", en: "Vieng Savan Village" },
            { la: "ບ້ານທົ່ງປົ່ງ", en: "Thong Pong Village" },
            { la: "ບ້ານນາເລົ່າ", en: "Na Leo Village" },
            { la: "ບ້ານໜອງໜ້ຽວ", en: "Nong Nhiew Village" },
            { la: "ບ້ານໜອງແຕ່ງໃຕ້", en: "Nong Taeng Tai Village" },
            { la: "ບ້ານໜອງແຕ່ງເໜືອ", en: "Nong Taeng Nuea Village" },
            { la: "ບ້ານວຽງຄຳ", en: "Vieng Kham Village" },
            { la: "ບ້ານຈຳປາ", en: "Champa Village" },
            { la: "ບ້ານດົງນາໂຊກໃຕ້", en: "Dong Na Sok Tai Village" },
            { la: "ບ້ານດົງນາໂຊກເໜືອ", en: "Dong Na Sok Nuea Village" },
            { la: "ບ້ານປາກທ້າງ", en: "Pak Thang Village" },
            { la: "ບ້ານດົງນາທອງ", en: "Dong Na Thong Village" },
            { la: "ບ້ານຫຼັກຫີນ", en: "Lak Hin Village" },
            { la: "ບ້ານໜອງບຶກໃຕ້", en: "Nong Buk Tai Village" },
            { la: "ບ້ານໜອງບຶກເໜືອ", en: "Nong Buk Nuea Village" },
            { la: "ບ້ານດົງກະເລົາ", en: "Dong Ka Lao Village" },
            { la: "ບ້ານຊຳເກດ", en: "Cham Ket Village" },
            { la: "ບ້ານຂຸນຕາທົ່ງ", en: "Khun Ta Thong Village" },
            { la: "ບ້ານຂຸນຕາທ່າ", en: "Khun Ta Tha Village" },
            { la: "ບ້ານສີຖານເໜືອ", en: "Si Than Nuea Village" },
            { la: "ບ້ານໜອງດ້ວງເໜືອ", en: "Nong Duang Nuea Village" },
            { la: "ບ້ານໜອງດ້ວງໃຕ້", en: "Nong Duang Tai Village" },
            { la: "ບ້ານໜອງດ້ວງທົ່ງ", en: "Nong Duang Thong Village" },
            { la: "ບ້ານໂພນສະຫວາດໃຕ້", en: "Phon Savad Tai Village" },
            { la: "ບ້ານໜອງບົວທອງໃຕ້", en: "Nong Bou Thong Tai Village" },
            { la: "ບ້ານໜອງບົວທອງເໜືອ", en: "Nong Bou Thong Nuea Village" },
            { la: "ບ້ານໂພນຄຳ", en: "Phon Kham Village" },
            { la: "ບ້ານຈັນສະຫວ່າງ", en: "Chan Savan Village" },
            { la: "ບ້ານດອນຊິງຊູ່", en: "Don Ching Su Village" }
        ],

        "Sisattanak": [
            { la: "ບ້ານເພຍວັດ", en: "Pheuy Vat Village" },
            { la: "ບ້ານເກົ້າຍອດ", en: "Kao Yod Village" },
            { la: "ບ້ານສີເມືອງ", en: "Si Muang Village" },
            { la: "ບ້ານດົງປ່າລານທ່າ", en: "Dong Pa Lan Tha Village" },
            { la: "ບ້ານດົງປ່າລານທົ່ງ", en: "Dong Pa Lan Thong Village" },
            { la: "ບ້ານໜອງຈັນ", en: "Nong Chan Village" },
            { la: "ບ້ານໂພນສີນວນ", en: "Phon Sin Vone Village" },
            { la: "ບ້ານທາດຂາວ", en: "That Khao Village" },
            { la: "ບ້ານພະໄຊ", en: "Pha Sai Village" },
            { la: "ບ້ານພະໂພ", en: "Pha Pho Village" },
            { la: "ບ້ານບຶງຂະຫຍອງ", en: "Bung Kha Nyong Village" },
            { la: "ບ້ານໂສກປ່າຫຼວງ", en: "Sok Pa Luang Village" },
            { la: "ບ້ານໂພນສະຫວັນເໜືອ", en: "Phon Savan Nuea Village" },
            { la: "ບ້ານໂພນສະຫວັນໃຕ້", en: "Phon Savan Tai Village" },
            { la: "ບ້ານວັດນາກ", en: "Wat Nak Village" },
            { la: "ບ້ານທົ່ງກາງ", en: "Thong Kang Village" },
            { la: "ບ້ານທ່າພະລານໄຊ", en: "Tha Phalan Sai Village" },
            { la: "ບ້ານດອນປ່າໃໝ່", en: "Don Pa Mai Village" },
            { la: "ບ້ານທົ່ງພານທອງ", en: "Thong Phan Thong Village" },
            { la: "ບ້ານສະພານທອງເໜືອ", en: "Saphan Thong Nuea Village" },
            { la: "ບ້ານສະພານທອງໃຕ້", en: "Saphan Thong Tai Village" },
            { la: "ບ້ານດອນນົກຂຸ້ມ", en: "Don Nok Khum Village" },
            { la: "ບ້ານໂພນປ່າເປົ້າ", en: "Phon Pa Pao Village" },
            { la: "ບ້ານດອນກອຍ", en: "Don Koi Village" },
            { la: "ບ້ານດົງສະຫວາດ", en: "Dong Savad Village" },
            { la: "ບ້ານໂພໄຊ", en: "Pho Sai Village" },
            { la: "ບ້ານສ້າງເຫວີຍ", en: "Sang Heuy Village" },
            { la: "ບ້ານພັນໝັ້ນ", en: "Phan Man Village" },
            { la: "ບ້ານວັດສົບ", en: "Wat Sop Village" },
            { la: "ບ້ານສວນມອນ", en: "Suan Mon Village" },
            { la: "ບ້ານຫາຍໂສກ", en: "Hai Sok Village" },
            { la: "ບ້ານໂຄກນິນ", en: "Kok Nin Village" },
            { la: "ບ້ານໂພນສະຫວ່າງ", en: "Phon Savan Village" },
            { la: "ບ້ານໄຊສະຖານ", en: "Xai Sathan Village" },
            { la: "ບ້ານຈອມແຈ້ງ", en: "Chom Jaeng Village" },
            { la: "ບ້ານຈອມເພັດເໜືອ", en: "Chom Phet Nuea Village" },
            { la: "ບ້ານຈອມເພັດໃຕ້", en: "Chom Phet Tai Village" }
        ],

        "Hardxaiyfong": [
            { la: "ບ້ານຖິ່ນຈົມ", en: "Ban Thin Chom Village" },
            { la: "ບ້ານໜອງໄຮ", en: "Ban Nong Hai Village" },
            { la: "ບ້ານຫ້ອມ", en: "Ban Hom Village" },
            { la: "ບ້ານບໍໂອ", en: "Ban Bo O Village" },
            { la: "ບ້ານຈີນາຍໂມ້", en: "Ban Chinay Mo Village" },
            { la: "ບ້ານດົງຄຳຊ້າງ", en: "Ban Dong Kham Chang Village" },
            { la: "ບ້ານຫາດຊາຍຂາວ", en: "Ban Hat Sai Khao Village" },
            { la: "ບ້ານສົມຫວັງເໜືອ", en: "Ban Somvang Nuea Village" },
            { la: "ບ້ານສົມຫວັງໃຕ້", en: "Ban Somvang Tai Village" },
            { la: "ບ້ານສົມສະໜຸກ", en: "Ban Somsanuk Village" },
            { la: "ບ້ານດອນດູ່", en: "Ban Don Du Village" },
            { la: "ບ້ານທ່ານາ", en: "Ban Tha Na Village" },
            { la: "ບ້ານພ້າວ", en: "Ban Phaw Village" },
            { la: "ບ້ານຂາຊ້າຍ", en: "Ban Kha Sai Village" },
            { la: "ບ້ານກາງ", en: "Ban Kang Village" },
            { la: "ບ້ານແກ້ງຍາງ", en: "Ban Kaeng Yang Village" },
            { la: "ບ້ານສົມໂຮງ", en: "Ban Som Hong Village" },
            { la: "ບ້ານນາທາມ", en: "Ban Na Tham Village" }
        ],

        "Naxaiythong": [
            { la: "ໂຊກມະນີ", en: "Sokmanee Village" },
            { la: "ສີເກີດ", en: "Si Koet Village" },
            { la: "ພຽງຫຼວງ", en: "Phieng Luang Village" },
            { la: "ມາຊຽງ", en: "Ma Xiang Village" },
            { la: "ດົງຈອງ", en: "Dong Chong Village" },
            { la: "ໂພນສະຫວັນ", en: "Phon Savan Village" },
            { la: "ໂພນແກ້ວ", en: "Phon Kaeo Village" },
            { la: "ນາສີຊຽງ", en: "Na Si Xiang Village" },
            { la: "ດົງຈງກົ", en: "Dong Chong Ko Village" },
            { la: "ພຽງຊາວ", en: "Phieng Chao Village" },
            { la: "ດົງຈອງ", en: "Dong Chong Village" },
            { la: "ນາຕູນໃຕ້", en: "Na Tun Tai Village" },
            { la: "ນາຕູນເໜືອ", en: "Na Tun Nuea Village" },
            { la: "ນາຊາຍທອງໃຕ້", en: "Na Sai Thong Tai Village" },
            { la: "ນາຊາຍທອງກາງ", en: "Na Sai Thong Kang Village" },
            { la: "ນາຊາຍທອງເໜືອ", en: "Na Sai Thong Nuea Village" },
            { la: "ດົງຊ້າງ", en: "Dong Chang Village" },
            { la: "ນາອຸດົມ", en: "Na Udom Village" },
            { la: "ດົງບົວ", en: "Dong Bua Village" },
            { la: "ພຽງສີງນຸດ", en: "Phieng Sing Nut Village" },
            { la: "ນາທີ່ຈງໃຕ້", en: "Na Thi Chom Tai Village" },
            { la: "ນາທີ່ຈງເໜືອ", en: "Na Thi Chom Nuea Village" },
            { la: "ນາຊັບ", en: "Na Sap Village" },
            { la: "ນາເປົ່າ", en: "Na Pao Village" },
            { la: "ຊໍາໄຮໃຕ້", en: "Sam Hai Tai Village" },
            { la: "ຊໍາໄຮເໜືອ", en: "Sam Hai Nuea Village" },
            { la: "ສີງວິລາງແສນ", en: "Sing Vilang Saen Village" },
            { la: "ແຂວງສະຫວ່າງ", en: "Khuaeng Savan Village" },
            { la: "ສີສະຫວາດ", en: "Si Savad Village" },
            { la: "ຫ້ວຍນໍ້າເປັນ", en: "Huay Nam Pen Village" },
            { la: "ນາຊຸມ", en: "Na Chum Village" },
            { la: "ພຽງເປືອຍໃຕ້", en: "Phieng Peuy Tai Village" },
            { la: "ພຽງເປືອຍເໜືອ", en: "Phieng Peuy Nuea Village" },
            { la: "ໂພນຄາ", en: "Phon Kha Village" },
            { la: "ຫ້ວຍດາ", en: "Huay Da Village" },
            { la: "ນາຫຼວງ", en: "Na Luang Village" },
            { la: "ພູດັ່ງ", en: "Phu Dang Village" },
            { la: "ແສນດິນ", en: "Saen Din Village" },
            { la: "ດົງຈັງ", en: "Dong Chang Village" },
            { la: "ນາຊ່າ", en: "Na Cha Village" },
            { la: "ໂພນມ່ວງ", en: "Phon Muang Village" },
            { la: "ນາຊຸ່ມ", en: "Na Chum Village" },
            { la: "ບົວ", en: "Bua Village" },
            { la: "ພັດທະນາ", en: "Phatthana Village" },
            { la: "ຫ້ວຍສະ", en: "Huay Sa Village" },
            { la: "ນາຄໍາ", en: "Na Kham Village" },
            { la: "ໂພນຕອງ", en: "Phon Tong Village" },
            { la: "ໂພໄຊ", en: "Pho Sai Village" },
            { la: "ໂພສີ", en: "Pho Si Village" },
            { la: "ສີງວິໄລ", en: "Sing Vilai Village" },
            { la: "ຫ້າ", en: "Ha Village" },
            { la: "ນາຫ້ອມ", en: "Na Hom Village" },
            { la: "ຫ້ວຍນໍ້າຕຸນ", en: "Huay Nam Tun Village" },
            { la: "ນາປາງ", en: "Na Pang Village" },
            { la: "ຄໍາລືສີ", en: "Kham Lue Si Village" },
            { la: "ນາໂທນແສງ", en: "Na Thon Saeng Village" }
        ],

        "Xaythany": [
            { "la": "ບ້ານຂຸດສາມບາດ", "en": "Khut Sam Bat Village" },
            { "la": "ບ້ານທົ່ງມັ່ງ", "en": "Thong Mang Village" },
            { "la": "ບ້ານນາກຸງ", "en": "Na Kung Village" },
            { "la": "ບ້ານໂພນຄໍ້", "en": "Phon Kho Village" },
            { "la": "ບ້ານຫາດກ້ຽງ", "en": "Hat Kieng Village" },
            { "la": "ບ້ານໂພນໂຮງ", "en": "Phon Hong Village" },
            { "la": "ບ້ານໂພນໄຮຄຳ", "en": "Phon Hai Kham Village" },
            { "la": "ບ້ານໄຮ່", "en": "Hai Village" },
            { "la": "ບ້ານທ່າສະຫວ່າງ", "en": "Tha Savan Village" },
            { "la": "ບ້ານເວີນຄຳ", "en": "Vien Kham Village" },
            { "la": "ບ້ານຈະເລີນໄຊ", "en": "Cha Lern Sai Village" },
            { "la": "ບ້ານໜອງເຂັງ", "en": "Nong Khaeng Village" },
            { "la": "ບ້ານໜອງໂນ", "en": "Nong No Village" },
            { "la": "ບ້ານໂພນງາມ", "en": "Phon Ngam Village" },
            { "la": "ບ້ານໂພນໄຊ", "en": "Phon Sai Village" },
            { "la": "ບ້ານສາມສະອາດ", "en": "Sam Sa At Village" },
            { "la": "ບ້ານທ່າງ່ອນ", "en": "Thang On Village" },
            { "la": "ບ້ານນາ", "en": "Na Village" },
            { "la": "ບ້ານພູຄຳ", "en": "Phu Kham Village" },
            { "la": "ບ້ານແກ້ງໄຄ້", "en": "Kaeng Khai Village" },
            { "la": "ບ້ານທ່າສົມມໍ", "en": "Tha Som Moth Village" },
            { "la": "ບ້ານອຸດົມຜົນ", "en": "Udom Phon Village" },
            { "la": "ບ້ານລາດຄວາຍ", "en": "Lat Khwai Village" },
            { "la": "ບ້ານໂນນແຕ້", "en": "Non Tae Village" },
            { "la": "ບ້ານໂນນສະອາດ", "en": "Non Sa At Village" },
            { "la": "ບ້ານດົງໝາກຄວາຍ", "en": "Dong Mak Khwai Village" },
            { "la": "ບ້ານດ່ານຊ້າງ", "en": "Dan Chang Village" },
            { "la": "ບ້ານດອນຕິ້ວ", "en": "Don Tiu Village" },
            { "la": "ບ້ານໄຊສະຫວ່າງ", "en": "Sai Savan Village" },
            { "la": "ບ້ານດອນໜູນ", "en": "Don Noon Village" },
            { "la": "ບ້ານໄຊ", "en": "Sai Village" },
            { "la": "ບ້ານນາແຄ", "en": "Na Khae Village" },
            { "la": "ບ້ານສະພັງເມິກ", "en": "Saphang Mek Village" },
            { "la": "ບ້ານຊ້າງຄູ້", "en": "Chang Khu Village" },
            { "la": "ບ້ານພະຂາວ", "en": "Pha Khaw Village" },
            { "la": "ບ້ານສີວິໄລ", "en": "Si Vilai Village" },
            { "la": "ບ້ານຄຳຮຸ່ງ", "en": "Kham Hung Village" },
            { "la": "ບ້ານໜອງວຽງຄຳ", "en": "Nong Vieng Kham Village" },
            { "la": "ບ້ານຫ້ວຍແດນເມືອງ", "en": "Huay Dan Mueang Village" },
            { "la": "ບ້ານຕາມມີໄຊ", "en": "Tam Mi Sai Village" },
            { "la": "ບ້ານໜອງພະຍາ", "en": "Nong Phaya Village" },
            { "la": "ບ້ານນາທົ່ມ", "en": "Na Thom Village" },
            { "la": "ບ້ານວຽງແກ້ວ", "en": "Vieng Kaeo Village" },
            { "la": "ບ້ານໂນນແສງຈັນ", "en": "Non Saeng Chan Village" },
            { "la": "ບ້ານຫ້ວຍເຕີຍ", "en": "Huay Toei Village" },
            { "la": "ບ້ານດົງສ້າງຫີນ", "en": "Dong Sang Hin Village" },
            { "la": "ບ້ານໂພຄຳ", "en": "Phon Kham Village" },
            { "la": "ບ້ານໂຄກນ້ອຍ", "en": "Khok Noi Village" },
            { "la": "ບ້ານນາໂຄກໃຫຍ່", "en": "Na Khok Yai Village" }
        ],

        "Sungthong": [
            { la: "ບ້ານຊຽງແລນາ", en: "Sieng Lana Village" },
            { la: "ບ້ານເວີນກະເບົາ", en: "Vern Kabeo Village" },
            { la: "ບ້ານໂນນ", en: "Non Village" },
            { la: "ບ້ານໂພນຂາມ", en: "Phon Kham Village" },
            { la: "ບ້ານຫົວນາທົ່ງ", en: "Hua Na Thong Village" },
            { la: "ບ້ານນາບົງ", en: "Na Bong Village" },
            { la: "ບ້ານທ່າກົກໄຮ", en: "Tha Kok Hai Village" },
            { la: "ບ້ານໜອງດົງ", en: "Nong Dong Village" },
            { la: "ບ້ານຫ້ວຍນໍ້າຢຸນ", en: "Huay Nam Yun Village" },
            { la: "ບ້ານທ່າຊ້າງ", en: "Tha Chang Village" },
            { la: "ບ້ານຊຽງແລທ່າ", en: "Sieng La Tha Village" },
            { la: "ບ້ານຝັງແດງ", en: "Fang Daeng Village" },
            { la: "ບ້ານປາກກວາງ", en: "Pak Kwang Village" },
            { la: "ບ້ານເວີນແຄນ", en: "Vern Khaen Village" },
            { la: "ບ້ານສົມປະເສີດ", en: "Som Pasert Village" },
            { la: "ບ້ານໄຮ່", en: "Hai Village" },
            { la: "ບ້ານໂນນຊາຍ", en: "Non Sai Village" },
            { la: "ບ້ານດອນສັງຄີ", en: "Don Sangkhie Village" },
            { la: "ບ້ານທຸນລົວ", en: "Thun Luea Village" },
            { la: "ບ້ານພ້າວ", en: "Phaw Village" },
            { la: "ບ້ານດອນແຍງ", en: "Don Yaeng Village" },
            { la: "ບ້ານທ່າກອກ", en: "Tha Kok Village" },
            { la: "ບ້ານນາກຸງ", en: "Na Kung Village" },
            { la: "ບ້ານໜອງພູວຽງ", en: "Nong Phu Vieng Village" },
            { la: "ບ້ານນາຊອນ", en: "Na Son Village" },
            { la: "ບ້ານນາທາມ", en: "Na Tham Village" },
            { la: "ບ້ານໜອງແຄນ", en: "Nong Khaen Village" }
        ],

        "Parknguem": [
            { la: "ບ້ານຊຽງແລນາ", en: "Xieng Lana Village" },
            { la: "ບ້ານເວີນກະເບົາ", en: "Vien Kabeo Village" },
            { la: "ບ້ານໂນນ", en: "Non Village" },
            { la: "ບ້ານໂພນຂາມ", en: "Phon Kham Village" },
            { la: "ບ້ານຫົວນາທົ່ງ", en: "Hua Na Thong Village" },
            { la: "ບ້ານນາບົງ", en: "Na Bong Village" },
            { la: "ບ້ານທ່າກົກໄຮ", en: "Tha Kok Hai Village" },
            { la: "ບ້ານໜອງດົງ", en: "Nong Dong Village" },
            { la: "ບ້ານຫ້ວຍນໍ້າຢຸນ", en: "Huay Nam Yun Village" },
            { la: "ບ້ານທ່າຊ້າງ", en: "Tha Chang Village" },
            { la: "ບ້ານຊຽງແລທ່າ", en: "Xieng La Tha Village" },
            { la: "ບ້ານຝັງແດງ", en: "Fang Daeng Village" },
            { la: "ບ້ານປາກກວາງ", en: "Pak Kwang Village" },
            { la: "ບ້ານເວີນແຄນ", en: "Vien Kaen Village" },
            { la: "ບ້ານສົມປະເສີດ", en: "Sompasert Village" },
            { la: "ບ້ານໄຮ່", en: "Hai Village" },
            { la: "ບ້ານໂນນຊາຍ", en: "Non Sai Village" },
            { la: "ບ້ານດອນສັງຄີ", en: "Don Sangki Village" },
            { la: "ບ້ານທຸນລົວ", en: "Thun Luang Village" },
            { la: "ບ້ານພ້າວ", en: "Phaw Village" },
            { la: "ບ້ານດອນແຍງ", en: "Don Yaeng Village" },
            { la: "ບ້ານທ່າກອກ", en: "Tha Kok Village" },
            { la: "ບ້ານນາກຸງ", en: "Na Kung Village" },
            { la: "ບ້ານໜອງພູວຽງ", en: "Nong Phu Vieng Village" },
            { la: "ບ້ານນາຊອນ", en: "Na Son Village" },
            { la: "ບ້ານນາທາມ", en: "Na Tham Village" },
            { la: "ບ້ານໜອງແຄນ", en: "Nong Kaen Village" },
            { la: "ບ້ານດອນສ້າງໄພ", en: "Don Sang Phai Village" },
            { la: "ບ້ານໂພນສົມບູນ", en: "Phon Sombun Village" },
            { la: "ບ້ານໜອງບົວທອງ", en: "Nong Bua Thong Village" },
            { la: "ບ້ານໂຄກສາ", en: "Khok Sa Village" },
            { la: "ບ້ານດອນໄຮ່", en: "Don Hai Village" },
            { la: "ບ້ານທາງໂຄ້ງ", en: "Thang Khong Village" },
            { la: "ບ້ານໂນນສູງ", en: "Non Sung Village" },
            { la: "ບ້ານນາເລີດ", en: "Na Loet Village" },
            { la: "ບ້ານໜອງວັງເຜິ້ງ", en: "Nong Wang Pheng Village" },
            { la: "ບ້ານໂດນໃຕ້", en: "Don Tai Village" },
            { la: "ບ້ານໂດນເໜືອ", en: "Don Nuea Village" },
            { la: "ບ້ານດົງກະລຶມ", en: "Dong Kalum Village" },
            { la: "ບ້ານດົງສານ", en: "Dong San Village" },
            { la: "ບ້ານທ່າເດືອສິງຫອມ", en: "Tha Duea Sing Hom Village" },
            { la: "ບ້ານຖິ່ນທ່ຽງ", en: "Thin Thieng Village" },
            { la: "ບ້ານດອນວັງໂພ", en: "Don Wang Pho Village" },
            { la: "ບ້ານໝາກນາວໃຕ້", en: "Mak Naow Tai Village" },
            { la: "ບ້ານໝາກນາວເໜືອ", en: "Mak Naow Nuea Village" },
            { la: "ບ້ານນາຊາ", en: "Na Sa Village" },
            { la: "ບ້ານໝາກໜາວດົງ", en: "Mak Naw Dong Village" },
            { la: "ບ້ານນາຝາຍ", en: "Na Fai Village" },
            { la: "ບ້ານສ້າງໄສ", en: "Sang Sai Village" },
            { la: "ບ້ານໝາກຮຽວ", en: "Mak Hiew Village" },
            { la: "ບ້ານສົມສະຫວາດ", en: "Som Savat Village" },
            { la: "ບ້ານປາກງື່ມ", en: "Pak Ngum Village" },
            { la: "ບ້ານໜອງຂຽດ", en: "Nong Kiet Village" }
        ]
    },

};

export default laosData;